### PR TITLE
Re factor reduce stdout 08 03 2021

### PR DESCRIPTION
**Pull request by Vacant0mens**
replaced all `print` commands with `logging`
refactored and reformatted code to conform with pylint.

### CODE REVIEW

**Comment by b-morgan** [comment]
Can you please provide an example settings.json file.

**Comment by Vacant0mens** [comment]
if you look at lines 22 and 23, the only thing that would be required from the settings.json file would be `ApiKey`
so `{ "ApiKey": "YOURAPIKEY" }` would be enough.
Also, if you use command line parameters, you shouldn't need a settings.json file (likes 29-51). 

However, I will go back and revisit the command line options section, as it's only looking for the `api_key` variable, but then includes other options.

**Comment by Vacant0mens** [comment]
@b-morgan 
I've updated to include an example `settings.json` file, as well as separated the handling of both the `LogLevel`/`-l | --loglevel` and `ApiKey`/`-a | --apikey` settings, as well as changed the order of operations so that command line parameters take precedence over settings.json items.

**Comment by b-morgan** [comment]
Excellent changes, thank you. 

I've been testing / debugging with Thonny Python IDE and I haven't figured out how to run the program with command line arguments.

Here's a thought, add the latitude an longitude as options in the settings.json file (and the command line?). 

I've changed units=metric to units=imperial so this might be another candidate. The goal here would be to make changes to the source code unnecessary. 

One last issue which I consider a bug more that a feature request. Line 18, path statement needs an OS specific path separator instead of "\\" (or "//") at the end. I can't find a function for that but [os.path.normpath](https://docs.python.org/3/library/os.path.html) looks like it might do the trick (i.e. add the forward slash and then normpath it).

**Comment by Vacant0mens** [comment]
ah, yeah. must have missed those when I was refactoring stuff. try this last commit.

**Comment by b-morgan** [comment]
I hate to be rude but did you test your latest change? Changing the name of the variable doesn't fix the problem, current_hour is never initialized and if it is initialized, it has to be the %I, (12 hour variant), not %H, (24 hour variant). If it is %H then the clock works when the current time is AM and fails when the current time is PM.

**Comment by b-morgan** [comment]
> looks like your patch is just replacing `current_hour` with `hour_cursor`. Did that fix the problem?

current_hour is a local variable in the function update_forecast. It is not defined in the function get_mouse_click_coordinate.

hour_cursor is a global variable initialized in the functions update_forecast and get_mouse_click_coordinate. Not sure it needs to be global since it is initialized differently in the two functions.

currentHour was a local variable that was used in get_mouse_click_coordinate but never initialized. It was initialized at the top level to zero but never updated.

The version of the program that I attached in my zip file works (i.e. it fixes the problem).

Does that explain it better?

**Comment by Vacant0mens** [comment]
`hour_cursor` does need to be global since it's heavily used in the `while` loop at the end.

I tested this last commit, and it looks good in a PM time. I replaced `current_hour` like you did, but I also made sure that both functions have a `strftime("%p")` in them (I reduced some logic to find it in one of the functions).

**Comment by b-morgan** [comment]
We are almost there... During the hour from 12 noon to 1pm, touching 1 o'clock results in the display of next day, 1am. I haven't tested from 12 midnight to 1am yet.

BTW, logging.debug(cursor_x,cursor_y) doesn't work, it needs to be something like:
	logging.debug("cursor_x= " + str(cursor_x) + ", cursor_y= " + str(cursor_y))

**Comment by 0x0lli** [comment]
how about constantly displaying the upcoming 11 hours?
That way, only one icon would need to (drastically) change for every passed hour.
The current time is displayed via the pointer, so there is is no confusion. 
Are you able to see the correct icons and hide the taskbar? I am not.

**Comment by pjockey** [comment]
Is there a way to lock the screen from moving around when the screen is touched to update or look at different information?

**Comment by b-morgan** [comment]
> Is there a way to lock the screen from moving around when the screen is touched to update or look at different information?

It doesn't move around at all for me so I guess I don't understand what is happening to you.

**Comment by pjockey** [comment]
I'm running it thru VNC. Not sure if that has anything to do with it.

**Comment by b-morgan** [comment]
I also run through VNC and don't have a problem. I have a RPi Zero W with the Pimoroni HyperPixel 4.0 Square Touch display but I also am testing on an RPi 3B+ with a 1920x1080 HDMI display (no touch) with a mouse and keyboard.

Aside from a bug involving midnight and noon, the only issue I'm having is on the RPi 0W. The display is not centered in the case because it displays in a window with a title bar, i.e. I can't duplicate the display as shown in the video posted with the original project. All my attempts to create a borderless fullscreen have failed.

On the RPi 3B+, I have changed the wn.setup from `wn.setup(width=1.0, height=1.0)` to `wn.setup(width=0.3, height=0.5)` so it doesn't occupy the entire screen and I can see the debug output. Even in this case, the clock doesn't move around as I click on it.

**Comment by 0x0lli** [comment]
Thank your for clarifying that. Running the configured .py of the main branch that is a month old or your current development state from few days ago via ```python3 weatherClock.py``` makes no difference to me or I am ignorant to what the difference might be. 
I have the clock pointers moving in either case and showing the correct time. There is a significant lag with input via touchscreen and also, the need to touch the center in order to get rid of the shown details is not too intuitive. do you have differing icons displayed? I have all twelve icons showing a sun (which is the first count within the icons filenames).
I am wondering how the ad-video was made and where the founder of this project went. Maybe holidays? No reply to my email from two days ago yet.

**Comment by b-morgan** [comment]
IMO, the creator of this pull request should instead fork the original project and continue on independently. I have communicated with the original project creator but my most recent email has not been answered.

I prefer this version because of the use of the logging facility instead of all the print statements in the original, and the .json and command line inputs which eliminate the need to modify the source for most people (after we get all the bugs worked out).

When the clock hands are shown, you can touch any of the 12 hour icons to display the details for that hour. These details replace the clock hands and you must touch the center to clear the details and return the clock hands. The hour icons will change as the weather forecast for that hour changes.

I also wonder how the demonstration video was made. I have the identical hardware but I can't duplicate the video. My guess is that an unpublished version of the program was used.

**Comment by KeepThisTicket** [comment]
Greetings all - really appreciate all the efforts from everyone here to polish up the code and make it functionality wise way better ! I come from a hardware background so it's great to see all the helpful input. I have been pretty busy and away the last the few weeks but settling back in now, I will test the code and merge

I think there are actually a few differences in the code running on the device in the video such as an automatic full screen, I remember I did not add them back into the repo because the pi zero was so damn slow to load anything and I did not have a USB stick on hand. I will try to retrieve the changes and let you guys know here.

**Comment by Vacant0mens** [comment]
@0x0lli and @b-morgan 
I one of my changes in this PR was to make it close when the `x` was clicked. That may be contributing to the taskbar on top, I'll see about removing that bit as well as fixing the 12th-hour bug.

I personally would prefer to keep contributing to the main repo as long as there are people available to approve PR's. I realize that there are a lot of changes since I forked, but the main core of the code is still from the original creator.

**Comment by Vacant0mens** [comment]
These last two commits look good to me, but I'm also not testing on a RPi0 at the moment.

I hope this PR can get completed so that others can merge from master soon. My changes will probably cause a lot of conflicts with other PR's.

**Comment by Vacant0mens** [comment]
@b-morgan  I added similar logic to what you mentioned to skip the calculations, but I'm not seeing the display being incorrect for 12 noon/midnight. I tested with my clock at 12:45pm and clicking on hour 12 shows `Hour: 12pm`

**Pull request merged**
